---
name: Sys-Mmap-Simple
version: 0.14
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Memory mapping made simple and safe.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 5.57
  File::Map: 0.13
  Sub::Prototype: 0.02
  perl: 5.007003
build_requires:
  Test::More: 0
provides:
  Sys::Mmap::Simple:
    file: lib/Sys/Mmap/Simple.pm
    version: 0.14
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
