---
name: Sys-Mmap-Simple
version: 0.03_5
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Memory mapping made simple and safe.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  IO::Handle: 0
  Test::More: 0
  perl: 5.007003
  threads: 1.34
provides:
  Sys::Mmap::Simple:
    file: lib/Sys/Mmap/Simple.pm
    version: 0.03_5
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
